name: Image Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install podman-compose
      run: pip3 install podman-compose
    - name: Build the docker-compose stack
      run: podman-compose -f compose/container-compose.yml build
